### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by NicolasAgra** [tfio/pytest-gui#2]
Hello there, I would like to try this but I can not deploy the requirements because `requirements.txt` is missing.

Best Regards

**Comment by alysivji** [comment]
Went thru the code. Looks like the requirements are:

```
tkreadonly
guitest
pipes
```

I can't find the library for this line `from fs5test.utils.config import get_setting, update_settings, load_settings`

Would be great if this tool was on PyPI.

**Comment by hmurari** [comment]
Sorry it took some time to respond back on this.. But I spent some time today to resolve the spurious dependencies and checked in latest changes. Please try it and let me know if you would like any additional support. Thanks again for bringing this to my attention.
